/**
 * Documentation loader and Markdown preprocessor for the BabylonJS docs.
 *
 * The BabylonJS documentation has two families of files:
 *
 *   1. **API reference** — auto-generated by TypeDoc from TypeScript source.
 *      Each file has a breadcrumb header (`***` separators), an H1 like
 *      `# Class: Scene`, a `Defined in:` link, then the description.
 *
 *   2. **Guides / examples** — hand-written Markdown with YAML frontmatter
 *      (`title`, `description`, `keywords`, …) and an H1 heading.
 *
 * This module strips YAML frontmatter, extracts titles / descriptions /
 * headings, and builds a lightweight search index that holds the full
 * flattened body text of every page so search is comprehensive.
 */

import { readFileSync, readdirSync, statSync, existsSync } from "node:fs";
import { join, relative, dirname, basename, extname, sep } from "node:path";
import { fileURLToPath } from "node:url";

export interface DocEntry {
  /** Path relative to docs root without the `.md` extension, e.g. "api/core/src/classes/Scene". */
  path: string;
  /** Human-readable title (frontmatter > H1 > filename). */
  title: string;
  /** Optional one-line description from frontmatter or first paragraph. */
  description?: string;
  /** Top-level category, e.g. "api", "examples". */
  category: string;
  /** Absolute filesystem path of the underlying file. */
  filePath: string;
  /** Byte size of the raw file on disk. */
  size: number;
}

export interface DocIndexEntry extends DocEntry {
  /** All Markdown headings (H1–H4) concatenated for search scoring. */
  headings: string[];
  /** Full body text flattened (Markdown stripped) for full-text search. */
  bodyFlattened: string;
}

const DOCS_DIR_ENV =
  process.env.BABYLONJS_DOCS_PATH ?? process.env.BABYLONJS_DOCS_ROOT;
const PACKAGE_ROOT = dirname(fileURLToPath(import.meta.url));
const DEFAULT_DOCS_DIR = join(PACKAGE_ROOT, "..", "..", "docs");

let cachedIndex: DocIndexEntry[] | null = null;

/**
 * Resolve the docs directory. Precedence:
 *   1. BABYLONJS_DOCS_PATH / BABYLONJS_DOCS_ROOT env var (absolute path)
 *   2. <package_root>/docs (the docs shipped with this package)
 */
export function resolveDocsDir(): string {
  if (DOCS_DIR_ENV && existsSync(DOCS_DIR_ENV)) {
    return DOCS_DIR_ENV;
  }
  return DEFAULT_DOCS_DIR;
}

/** Walk a directory recursively and return every `.md` file. */
function walkMarkdown(dir: string, out: string[] = []): string[] {
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return out;
  }
  for (const entry of entries) {
    if (entry === "node_modules" || entry.startsWith(".")) continue;
    const full = join(dir, entry);
    let st;
    try {
      st = statSync(full);
    } catch {
      continue;
    }
    if (st.isDirectory()) {
      walkMarkdown(full, out);
    } else if (st.isFile() && extname(entry) === ".md") {
      out.push(full);
    }
  }
  return out;
}

/** Parse a YAML-like frontmatter block. We only need `title` and `description`. */
function parseFrontmatter(raw: string): {
  frontmatter: Record<string, string>;
  body: string;
} {
  if (!raw.startsWith("---")) return { frontmatter: {}, body: raw };
  const end = raw.indexOf("\n---", 3);
  if (end === -1) return { frontmatter: {}, body: raw };
  const yaml = raw.slice(3, end).trim();
  const body = raw.slice(end + 4).replace(/^\n/, "");
  const frontmatter: Record<string, string> = {};
  for (const line of yaml.split(/\r?\n/)) {
    const m = line.match(/^([A-Za-z_][A-Za-z0-9_-]*)\s*:\s*(.*)$/);
    if (!m) continue;
    const value = m[2]
      .trim()
      .replace(/^"(.*)"$/, "$1")
      .replace(/^'(.*)'$/, "$1");
    frontmatter[m[1]] = value;
  }
  return { frontmatter, body };
}

/** Convert a docs root + absolute file path to a relative path without `.md`. */
function filePathToPath(docsRoot: string, filePath: string): string {
  const rel = relative(docsRoot, filePath).replace(/\\/g, "/");
  return rel.replace(/\.md$/, "");
}

/** Convert a path to a category (top-level segment). */
function pathToCategory(docPath: string): string {
  const seg = docPath.split("/")[0];
  return seg || "root";
}

/** Turn a filename into a human-readable title. */
function humanizeFilename(filePath: string): string {
  const name = basename(filePath, ".md");
  return name
    .split(/[-_.]+/)
    .filter(Boolean)
    .map((w) => (/^[0-9]/.test(w) ? w : w[0].toUpperCase() + w.slice(1)))
    .join(" ");
}

/**
 * Extract the first H1 heading from Markdown text (frontmatter already
 * stripped). Returns the heading text without the leading `#` and kind
 * prefix for TypeDoc-style headings.
 */
function extractTitle(body: string): string | undefined {
  const m = body.match(/^\s*#\s+(.+?)\s*$/m);
  if (!m) return undefined;
  const heading = m[1].trim();
  // TypeDoc headings look like "# Class: Scene", "# Interface: IFoo", etc.
  // Keep the full heading — it's descriptive and searchable.
  return heading;
}

/**
 * Extract a description: from frontmatter, or the first substantial paragraph
 * after the H1 / "Defined in:" line.
 */
function extractDescription(
  frontmatter: Record<string, string>,
  body: string,
): string | undefined {
  if (frontmatter.description) return frontmatter.description;
  // For TypeDoc: find the first paragraph after "Defined in:" line
  const lines = body.split(/\r?\n/);
  let afterDefinedIn = false;
  let afterH1 = false;
  for (const line of lines) {
    const trimmed = line.trim();
    if (/^#\s+/.test(trimmed)) {
      afterH1 = true;
      continue;
    }
    if (afterH1 && /^Defined in:/.test(trimmed)) {
      afterDefinedIn = true;
      continue;
    }
    // Skip breadcrumb navigation lines (links + horizontal rules)
    if (/^\[.*\]\(.*\)/.test(trimmed)) continue;
    if (/^\*\*\*$/.test(trimmed)) continue;
    if (trimmed.startsWith("[@babylonjs")) continue;
    if (afterDefinedIn || (afterH1 && trimmed !== "")) {
      // First real paragraph
      if (trimmed === "") continue;
      // Skip "Defined in:" and "## See" etc.
      if (/^(Defined in|##|>|\*\*|<!)/.test(trimmed)) continue;
      const clean = trimmed
        .replace(/\[([^\]]*)\]\([^)]*\)/g, "$1")
        .replace(/[*`]/g, "");
      if (clean.length > 10) return clean.slice(0, 200);
    }
  }
  return undefined;
}

/** Extract all Markdown headings (H1–H4). */
function extractHeadings(body: string): string[] {
  const matches = body.match(/^#{1,4}\s+.+$/gm) || [];
  return matches.map((h) => h.replace(/^#{1,4}\s+/, "").trim());
}

/**
 * Flatten Markdown body to plain text for search indexing.
 * Strips code blocks, inline code, emphasis, links, headings markers.
 */
function flattenMarkdown(body: string): string {
  return body
    .replace(/```[\s\S]*?```/g, " ") // drop fenced code blocks
    .replace(/~~~[\s\S]*?~~~/g, " ") // drop tilde-fenced code blocks
    .replace(/`([^`]+)`/g, "$1") // inline code → text
    .replace(/!\[([^\]]*)\]\([^)]*\)/g, " ") // images
    .replace(/\[([^\]]*)\]\([^)]*\)/g, "$1") // links → label text
    .replace(/^#{1,6}\s+/gm, " ") // heading markers
    .replace(/^>\s+/gm, " ") // blockquotes
    .replace(/^[-*+]\s+/gm, " ") // list markers
    .replace(/^\d+\.\s+/gm, " ") // ordered list markers
    .replace(/^\*\*\*$/gm, " ") // horizontal rules
    .replace(/[*_~>#|-]/g, " ") // emphasis / table chars
    .replace(/\s+/g, " ")
    .trim();
}

/** Strip YAML frontmatter from raw Markdown, returning just the body. */
export function stripFrontmatter(raw: string): string {
  const { body } = parseFrontmatter(raw);
  return body;
}

export interface DirEntry {
  name: string;
  type: "directory" | "file";
  /** Relative path (without .md for files). */
  path: string;
  /** Number of `.md` files in a subdirectory (recursive). */
  fileCount?: number;
}

/** List the contents of a single directory within the docs root. */
export function listDirectory(
  docPath: string = "",
  docsRoot: string = resolveDocsDir(),
): { path: string; entries: DirEntry[] } {
  const target = docPath ? join(docsRoot, docPath) : docsRoot;
  if (!target.startsWith(docsRoot)) {
    throw new Error("Path traversal not allowed");
  }
  if (!existsSync(target)) {
    throw new Error(`Directory not found: ${docPath}`);
  }
  const items = readdirSync(target).sort();
  const result: DirEntry[] = [];
  for (const item of items) {
    if (item === "node_modules" || item.startsWith(".")) continue;
    const full = join(target, item);
    let st;
    try {
      st = statSync(full);
    } catch {
      continue;
    }
    const rel = docPath ? `${docPath}/${item}` : item;
    if (st.isDirectory()) {
      result.push({
        name: item,
        type: "directory",
        path: rel,
        fileCount: countMarkdown(full),
      });
    } else if (extname(item) === ".md") {
      result.push({
        name: item,
        type: "file",
        path: rel.replace(/\.md$/, ""),
      });
    }
  }
  return { path: docPath, entries: result };
}

/** Count `.md` files recursively. */
function countMarkdown(dir: string): number {
  let count = 0;
  try {
    const items = readdirSync(dir, { withFileTypes: true });
    for (const item of items) {
      if (item.name === "node_modules" || item.name.startsWith(".")) continue;
      if (item.isDirectory()) {
        count += countMarkdown(join(dir, item.name));
      } else if (extname(item.name) === ".md") {
        count++;
      }
    }
  } catch {
    /* ignore */
  }
  return count;
}

/** Discover every Markdown file under `docsRoot` and return their entries (un-loaded). */
export function listDocEntries(docsRoot: string = resolveDocsDir()): DocEntry[] {
  if (!existsSync(docsRoot)) return [];
  const files = walkMarkdown(docsRoot);
  const entries: DocEntry[] = [];
  for (const filePath of files) {
    const docPath = filePathToPath(docsRoot, filePath);
    let raw = "";
    try {
      raw = readFileSync(filePath, "utf8");
    } catch {
      continue;
    }
    const { frontmatter, body } = parseFrontmatter(raw);
    const title =
      frontmatter.title || extractTitle(body) || humanizeFilename(filePath);
    const description = extractDescription(frontmatter, body);
    entries.push({
      path: docPath,
      title,
      description,
      category: pathToCategory(docPath),
      filePath,
      size: raw.length,
    });
  }
  entries.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
  return entries;
}

/**
 * Build the full search index. Every `.md` file is read, frontmatter stripped,
 * headings extracted, and body flattened. The index is cached for the process
 * lifetime.
 */
export function buildSearchIndex(
  docsRoot: string = resolveDocsDir(),
): DocIndexEntry[] {
  if (cachedIndex) return cachedIndex;
  const entries = listDocEntries(docsRoot);
  const out: DocIndexEntry[] = [];
  for (const entry of entries) {
    let raw: string;
    try {
      raw = readFileSync(entry.filePath, "utf8");
    } catch {
      continue;
    }
    const { body } = parseFrontmatter(raw);
    out.push({
      ...entry,
      headings: extractHeadings(body),
      bodyFlattened: flattenMarkdown(body),
    });
  }
  cachedIndex = out;
  return out;
}

/** Allow callers to invalidate the cache (e.g. file watcher). */
export function invalidateIndexCache(): void {
  cachedIndex = null;
}

/**
 * Read a single doc by its relative path. Reads the file fresh, strips
 * frontmatter, and returns the Markdown body.
 */
export function readDoc(
  docPath: string,
  docsRoot: string = resolveDocsDir(),
): { path: string; content: string; title: string } | undefined {
  // Normalise: strip leading/trailing slashes, allow .md suffix
  const normalized = docPath.replace(/^\/+|\/+$/g, "");
  // Try with and without .md extension
  const candidates = [
    join(docsRoot, normalized),
    join(docsRoot, normalized + ".md"),
  ];
  for (const candidate of candidates) {
    if (!candidate.startsWith(docsRoot)) continue;
    if (!existsSync(candidate)) continue;
    let st;
    try {
      st = statSync(candidate);
    } catch {
      continue;
    }
    if (!st.isFile()) continue;
    const raw = readFileSync(candidate, "utf8");
    const { frontmatter, body } = parseFrontmatter(raw);
    const title =
      frontmatter.title || extractTitle(body) || humanizeFilename(candidate);
    return { path: normalized, content: body, title };
  }
  return undefined;
}

/** Find a doc index entry by path, with fuzzy fallbacks. */
export function findDocByPath(
  candidates: string[],
  index: DocIndexEntry[] = buildSearchIndex(),
): DocIndexEntry | undefined {
  for (const candidate of candidates) {
    const normalized = candidate.replace(/^\/+|\/+$/g, "").replace(/\.md$/, "");
    if (!normalized) continue;
    // Direct match
    const direct = index.find((d) => d.path === normalized);
    if (direct) return direct;
    // Match by last segment(s)
    const segments = normalized.split("/");
    const lastTwo = segments.slice(-2).join("/");
    const byLast = index.find(
      (d) => d.path === lastTwo || d.path.endsWith("/" + lastTwo),
    );
    if (byLast) return byLast;
    // Filename match (last segment only)
    const lastOne = segments[segments.length - 1];
    if (lastOne) {
      const byFilename = index.find(
        (d) =>
          d.path === lastOne ||
          d.path.endsWith("/" + lastOne) ||
          basename(d.filePath, ".md") === lastOne,
      );
      if (byFilename) return byFilename;
    }
    // Title case-insensitive match
    const lower = normalized.toLowerCase();
    const byTitle = index.find(
      (d) => d.title.toLowerCase() === lower || d.title.toLowerCase().includes(lower),
    );
    if (byTitle) return byTitle;
  }
  return undefined;
}

/** Return top-level stats about the doc set. */
export function getDocsStats(
  docsRoot: string = resolveDocsDir(),
): { totalFiles: number; categories: Record<string, number> } {
  const index = buildSearchIndex(docsRoot);
  const categories: Record<string, number> = {};
  for (const entry of index) {
    categories[entry.category] = (categories[entry.category] || 0) + 1;
  }
  return { totalFiles: index.length, categories };
}

export const __testing = {
  parseFrontmatter,
  filePathToPath,
  humanizeFilename,
  extractTitle,
  extractDescription,
  flattenMarkdown,
  extractHeadings,
  stripFrontmatter,
};
